# Generated by Django 5.1 on 2024-08-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_alter_expenditure_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="budgeted",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
